### ISSUE TITLE
Cannot download the Mac version

### ISSUE THREAD

**Issue by psubhashish** [pculture/mirovideoconverter3#28]
There is probably some issue with the [Mac version](http://ftp.osuosl.org/pub/pculture.org/mirovideoconverter/mac/Miro%20Video%20Converter.dmg) of the Miro Video Converter as it doesn't download. Can you please share the download link for Mac and also update on the website? Thanks.

**Comment by cworth** [comment]
Hi all,

  Haven’t worked on the video converter in a few years, but let me know if you’d like me to look into this?

Colin

**Comment by psubhashish** [comment]
@cworth That would be great Colin. I couldn't find a working download link for Mac. Will really appreciate if you can add that here. Thanks.

BTW many Wikipedia contributors like myself use Miro Video Converter and all of us, the open source community, will remain indebted to this great work you and other friends involved with this project have done. I got to know about this from a colleague at the Wikimedia Foundation. Since then I am in love with this great tool. It is so awesome that I have been recommending this to many any other colleagues. :) Thank you so much for this.

**Comment by srkn** [comment]
It seems this is the new link http://getmiro.com/files/MiroVideoConverter.dmg, you can inspect it via http://getmiro.com/files

**Comment by cworth** [comment]
So, I'm afraid I advertised myself a bit falsely. I don't have access to 
the website or an association with pculture anymore, though I have some 
free cycles as a contractor. Not sure who is the person who has 
access/can fix this problem?

I appreciate the appreciation for my work on MVC :-)

Colin

**Comment by psubhashish** [comment]
Thanks @srknkrn. It works. @cworth no worries buddy. Cheers!
